import type { Employee } from './employee.types'

export const DEPARTMENTS = [
  'Ban Giám Đốc',
  'Engineering',
  'Design',
  'Marketing',
  'HR',
  'Finance',
  'Sales',
] as const

export const OFFICES = ['Hồ Chí Minh', 'Hà Nội', 'Đà Nẵng'] as const

export const STATUSES = [
  { value: 'active', label: 'Đang làm việc' },
  { value: 'on_leave', label: 'Nghỉ phép' },
  { value: 'inactive', label: 'Đã nghỉ' },
] as const

export const EMPLOYEES_MOCK: Employee[] = [
  {
    id: 'emp-1',
    employeeCode: 'YU-001',
    fullName: 'Lê Văn A',
    email: 'a.le@yuhub.vn',
    phone: '0901234567',
    department: 'Ban Giám Đốc',
    position: 'CEO',
    office: 'Hồ Chí Minh',
    joinDate: '2023-01-01',
    status: 'active',
    initials: 'LA',
  },
  {
    id: 'emp-2',
    employeeCode: 'YU-002',
    fullName: 'Nguyễn Thị Lan',
    email: 'lan.nguyen@yuhub.vn',
    phone: '0912345678',
    department: 'Design',
    position: 'Lead Designer',
    office: 'Hồ Chí Minh',
    joinDate: '2023-02-15',
    status: 'active',
    initials: 'NL',
  },
  {
    id: 'emp-3',
    employeeCode: 'YU-003',
    fullName: 'Trần Văn Minh',
    email: 'minh.tran@yuhub.vn',
    phone: '0987654321',
    department: 'Engineering',
    position: 'Senior Developer',
    office: 'Hà Nội',
    joinDate: '2023-03-10',
    status: 'active',
    initials: 'TM',
  },
  {
    id: 'emp-4',
    employeeCode: 'YU-004',
    fullName: 'Lê Thị Hoa',
    email: 'hoa.le@yuhub.vn',
    phone: '0978123456',
    department: 'Marketing',
    position: 'Marketing Manager',
    office: 'Đà Nẵng',
    joinDate: '2023-04-20',
    status: 'on_leave',
    initials: 'LH',
  },
  {
    id: 'emp-5',
    employeeCode: 'YU-005',
    fullName: 'Phạm Quốc Bảo',
    email: 'bao.pham@yuhub.vn',
    phone: '0934567890',
    department: 'HR',
    position: 'HR Specialist',
    office: 'Hồ Chí Minh',
    joinDate: '2023-05-05',
    status: 'active',
    initials: 'PB',
  },
  {
    id: 'emp-6',
    employeeCode: 'YU-006',
    fullName: 'Võ Thị Kim Anh',
    email: 'anh.vo@yuhub.vn',
    phone: '0945678901',
    department: 'Finance',
    position: 'Accountant',
    office: 'Hà Nội',
    joinDate: '2023-06-12',
    status: 'inactive',
    initials: 'VA',
  },
  {
    id: 'emp-7',
    employeeCode: 'YU-007',
    fullName: 'Đặng Nhật Huy',
    email: 'huy.dang@yuhub.vn',
    phone: '0967890123',
    department: 'Engineering',
    position: 'Frontend Developer',
    office: 'Hồ Chí Minh',
    joinDate: '2023-08-01',
    status: 'active',
    initials: 'ĐH',
  },
  {
    id: 'emp-8',
    employeeCode: 'YU-008',
    fullName: 'Bùi Thị Hà',
    email: 'ha.bui@yuhub.vn',
    phone: '0956789012',
    department: 'Sales',
    position: 'Sales Executive',
    office: 'Đà Nẵng',
    joinDate: '2023-09-15',
    status: 'active',
    initials: 'BH',
  },
]
